version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: events_platform
      POSTGRES_USER: root
      POSTGRES_PASSWORD: super_secret
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
